import { Inter, Archivo_Black } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Particles from "@/components/Particles";


const inter = Inter({ subsets: ["latin"] });
const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${[archivoBlack.className].join(" ")} relative min-h-screen overflow-hidden`}
      >
        {/* Background Particles */}
        <div className="absolute min-h-screen min-w-screen bg-black  inset-0 -z-10">
          <Particles
            particleColors={["#ffffff", "#ffffff"]}
            particleCount={200}
            particleSpread={10}
            speed={0.1}
            particleBaseSize={100}
            moveParticlesOnHover={false}
            alphaParticles={false}
            disableRotation={false}
          />
        </div>

        {/* Foreground Content */}
        <div className="relative  z-10">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
